### ISSUE TITLE
64 bit support?

### ISSUE THREAD

**Issue by bitfabrikken** [appcelerator-modules/ti.imagefactory#11]
Now that App Store requires 64 bit support, is there someone available for making it?

**Comment by speedyankur** [comment]
We really need iOS 64 bit support I'm also using this module in couple of my apps.

**Comment by ingo** [comment]
Please see https://github.com/appcelerator-modules/ti.imagefactory/releases

**Comment by bitfabrikken** [comment]
Thanks @ingo ingo :)
