### ISSUE TITLE
Error with remote image

### ISSUE THREAD

**Issue by necov** [appcelerator-modules/ti.imagefactory#12]
Hi,

When I'm trying to run a image through Imagefactory, i get this error:

[ERROR] [iphone, 8.1, undefined] {
  "nativeLocation": "+[TiImagefactoryModule imageTransform:withArgs:](TiImagefactoryModule.m:126)",
  "message": "Invalid type passed to function",
  "nativeReason": "expected: TiBlob, was: String",
  "line": 57,
  "column": 55,
  "stack": "[native code]\nonload"
}

Im using your latest version with 64 bit, and running 3.5.0 SDK. Any suggestions?

**Comment by necov** [comment]
Additional info: 

 Script Error {
[ERROR] :      column = 43;
[ERROR] :      line = 54;
[ERROR] :      message = "Invalid type passed to function";
[ERROR] :      nativeLocation = "+[TiImagefactoryModule imageTransform:withArgs:] (TiImagefactoryModule.m:126)";
[ERROR] :      nativeReason = "expected: TiBlob, was: String";
[ERROR] :      sourceURL = "file:///Users/nicolaivilladsen/Library/Developer/CoreSimulator/Devices/2CD455E2-0657-4686-87CB-24D4C1D1AD8A/data/Containers/Bundle/Application/53722BC0-E5B1-449A-98CF-7CCBDE3F9ACB/Opgavezonen.app/streaming_lib/streamingModule.js";
[ERROR] :      stack = "[native code]\ncreateRadioStreaming
[ERROR] :  }

**Comment by deckameron** [comment]
@necov,
This module works with local image only.

Try creating a httpRequest

var xhr = Ti.Network.createHTTPClient({
      onload : function(e) {
              var blob = xhr.responseData;
              newBlob = ImageFactory.compress(blob, 0.25);
      },
xhr.open('GET', ''http://www.youserver.com/yourimage.jpg);
xhr.send();

**Comment by hansemannn** [comment]
@deckameron Exactly! Download the image first, the process it.
