### ISSUE TITLE
Very unstable on Android

### ISSUE THREAD

**Issue by rpavez** [appcelerator-modules/ti.imagefactory#13]
For certain images that are either big or with many colors this module crash, I tried using try/catch which sometimes catch the error and sometimes just crash the complete app.
(Tried version 2.2.1) Gist: https://gist.github.com/rpavez/45ec3a6394d9a41baad8

I really would appreciate some help, recommendations to fix the issue or other similar module.

**Comment by sulthankareem** [comment]
I hav developed an application using imageFactory module.I hav cropped the image, then the problem is that while clicking the save button to save the image, the application unfortunately stops.Is this is due to memory exception ? .In that application i hav used two more modules along with imageFactory.

**Comment by max1020** [comment]
i am also having problems (with alloy) with the android module (below the imageAsThumbnail method). this method works on ios (the imageWithRoundedCorner function does not show rounded borders in ios either) but not on android:

    [ERROR] :  TiExceptionHandler: (main) [5845,15949] ----- Titanium Javascript Runtime Error -----
    [ERROR] :  TiExceptionHandler: (main) [0,15949] - In alloy/controllers/images.js:17,52
    [ERROR] :  TiExceptionHandler: (main) [0,15949] - Message: Uncaught Error: interface not implemented
    [ERROR] :  TiExceptionHandler: (main) [0,15949] - Source:                     var borderImage = ImageFactory.imageAsThumbnail(image, 80,
    [ERROR] :  V8Exception: Exception occurred at alloy/controllers/images.js:17: Uncaught Error: interface not implemented

images.js:

    var image = event.media;
    if (event.mediaType == Ti.Media.MEDIA_TYPE_PHOTO) {
    //not working in ios either var borderImage = ImageFactory.imageWithRoundedCorner(image,2,8);
    var borderImage = ImageFactory.imageAsThumbnail(image,80,2);
    var f = Titanium.Filesystem.getFile(Titanium.Filesystem.applicationDataDirectory, "dis_small.jpg"); 
    f.write(borderImage);
    console.log("image " + JSON.stringify(borderImage));
    $.profileUserImage.setImage(borderImage);
    }

**Comment by max1020** [comment]
the titanium blob methods work now in android as well: http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.Blob (http://developer.appcelerator.com/question/118694/image-resizing-and-more)
