### ISSUE TITLE
cant find module: ti.imagefactory for architecture x86_64

### ISSUE THREAD

**Issue by nathanflynn123** [appcelerator-modules/ti.imagefactory#14]
Hi I keep getting the following error (cant find module: ti.imagefactory for architecture x86_64). I have followed every suggested answer I could possibly find on the net, including editing the manifest file, editing the module setting in xcode, copy the url straight from the download link and pasting it into titaniums module insert. It appears in tiapp.xml but still nothing. 

I must add that this happens with all modules im using from github, so im assuming that if i solve this problem once, I should then be able to replicate the solution for them all. This how now held up my app development at this stage untill I can resolve this issue and is really frustrating, I would appreciate if anyone had any clear concise proven solutions.Many thanks in advance????

**Comment by WDPX** [comment]
I do have the same problem. So, this module isn't usable, anymore. So sad.

**Comment by ashcoding** [comment]
@WDPX could you describe what you are facing?

**Comment by WDPX** [comment]
Hi, I receive an error in the app when using the imagefactory that it doesn't have support for ARM 64 so it seems to be lacking a iOS 64 bit support. I tried it on an iPad mini 2 retina with iOS 9.2

**Comment by hansemannn** [comment]
Working for me. Please make sure you use the latest version and validate the tiapp.xm. Thx!
