### ISSUE TITLE
Android: java.lang.NullPointerException

### ISSUE THREAD

**Issue by sphairo** [appcelerator-modules/ti.imagefactory#16]
I am using Titanium SDK 4.1.0GA and ti.imagefactory 2.2.1

but my console print this:

at ti.imagefactory.ImageFactoryModule.compress(ImageFactoryModule.java:251)
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN] :   W/System.err:    at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:908)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1137)
[WARN] :   W/System.err:    at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:348)
[WARN] :   W/System.err:    at org.appcelerator.titanium.proxy.TiWindowProxy.handleMessage(TiWindowProxy.java:102)
[WARN] :   W/System.err:    at ti.modules.titanium.ui.WindowProxy.handleMessage(WindowProxy.java:428)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:136)
[WARN] :   W/System.err:    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)

My code en .js is:

var _imageFactory = require('ti.imagefactory');

function(imagen) { 
    return _imageFactory.compress(imagen, 0.60);
};

**Comment by hansemannn** [comment]
This should not be an issue on Android using the module 3.0.0 and later anymore.
