### ISSUE TITLE
Can't run on Android 6.0

### ISSUE THREAD

**Issue by neerup** [appcelerator-modules/ti.imagefactory#18]
Can't run with SDK 5.1 on Android 6.0 because of  text relocations

**Comment by andersdp** [comment]
Same here. App crashes immediately on launch when targetSdkVersion="23" but only on a real device.

**Comment by ashcoding** [comment]
Thanks for bringing this up. You would need to recompile the module to use it with the latest SDK 5.1.0

**Comment by ashcoding** [comment]
Created a ticket. Please follow it here: https://jira.appcelerator.org/browse/TIMOB-20056

Or alternatively, you could compile the module if you need it urgently. :)

**Comment by neerup** [comment]
This is the 64Bit problem with IOS modules all over again... the SDK is upgraded but the modules is not..
This renders SDK 5.1 GA useless if You use this module... 
Sorry for the language, but this is frustrating...

**Comment by andersdp** [comment]
@neerup Yeah, agree it's frustrating.

@ashcoding I hav'nt tried compiling a module before. How is it done?

**Comment by ashcoding** [comment]
You can get the compiled module here for Android 6.0 https://github.com/appcelerator-modules/ti.imagefactory/releases/tag/android-2.2.2

The changes required to compile is here: https://github.com/appcelerator-modules/ti.imagefactory/pull/19/files

You would also need a `build.properties` in the Android folder. The example is here: https://github.com/appcelerator-modules/ti.imagefactory/blob/stable/android/build.properties.example

An example that I use is:-
```
titanium.sdk=/Users/msamah/Library/Application Support/Titanium
titanium.os=osx
titanium.version=5.0.0.GA
android.sdk=/Users/msamah/Library/Android/sdk
android.ndk=/Users/msamah/Library/Android/android-ndk-r10e

titanium.platform=${titanium.sdk}/mobilesdk/${titanium.os}/${titanium.version}/android
android.platform=${android.sdk}/platforms/android-8
google.apis=${android.sdk}/add-ons/addon_google_apis_google_inc_8
```

**Comment by ashcoding** [comment]
@neerup @andersdp If there's any other modules causing similar issues for you, do create an issue and let me know so that I can attend to it.

**Comment by neerup** [comment]
@ashcoding ti.cloudpush has the same issue, so if you could recompile that aswell, That would be really nice. 
It already has an issue: https://jira.appcelerator.org/browse/MOD-2148

**Comment by ashcoding** [comment]
Yup. @neerup thanks for the info. It's recompiled. Currently under review. I'll nudge the ticket a bit to make it move.

**Comment by neerup** [comment]
@ashcoding Thanks it will be appreciated...

**Comment by andersdp** [comment]
Great, thanks @ashcoding :+1:

**Comment by ashcoding** [comment]
Closing the ticket.

**Comment by neerup** [comment]
@ashcoding Any chance of a link to the Cloudpush module ?

**Comment by ashcoding** [comment]
@neerup Ticket: https://jira.appcelerator.org/browse/MOD-2148
You can find it here: https://github.com/appcelerator/titanium_mobile/blob/master/support/module/packaged/ti.cloudpush-android-3.4.1.zip
