### ISSUE TITLE
Dist for ios

### ISSUE THREAD

**Issue by BeJedi** [appcelerator-modules/ti.imagefactory#21]
Where is dist folder/file for ios? how do i install it without zip package in ios?

**Comment by iMaciah** [comment]
Just go to the tab Releases (inside code).
<img width="758" alt="screen shot 2015-12-24 at 8 49 28 pm" src="https://cloud.githubusercontent.com/assets/6054107/11999258/db8a7982-aa7f-11e5-9247-7dd78179584f.png">

**Comment by BeJedi** [comment]
ah.. thanks. have we done anything about image rotation problem on resize or thumbnail?
