### ISSUE TITLE
Android: PX dimension support for Android

### ISSUE THREAD

**Issue by nitrag** [appcelerator-modules/ti.imagefactory#22]
In the iOS module the imageAsResized accounts for DP. Not Android. I'm resizing to 300x300 and the image is blurry. I had to manually account for the dp before sending to imageAsResized.

Is this intended? Seems annoying to have the modules be different.

**Comment by hansemannn** [comment]
@nitrag Still happening? And do you mean the density? Should be fixable in the Android source using the `TiConvert` class

**Comment by nitrag** [comment]
Can't say for sure, sorry, closing.
