### ISSUE TITLE
After compress the image clarity and quality missed?

### ISSUE THREAD

**Issue by ChanakyaSrinivas** [appcelerator-modules/ti.imagefactory#24]
Hi All,

I am using this module for compress the image.
After compressed that image it is giving less quality and clarity compared with original image.

Can any help me out, how to get image with full clarity and quality after compress or crop of original image also

**Comment by hansemannn** [comment]
@ChanakyaSrinivas That's why you compress it - to decrease the size and therefore the quality. Use the second parameter to specify a compression rate, e.g. `imageFactory.compress(image, 0);` for the lowest
