### ISSUE TITLE
Module not listed

### ISSUE THREAD

**Issue by obaidjawad** [appcelerator-modules/ti.imagefactory#27]
I have imported the module archive and also verified in the home location of modules in MAC OS. It is available but it is not listed in the module list when I click '+' in module section in tiapp.xml

Appcelerator Studio, build: 4.8.1.201612050850

And I manually added from the xml file 

`<module platform="android">ti.imagefactory</module>`

it says module is not supported with Titanium SDK 5.1.0GA

**Comment by hansemannn** [comment]
The latest version was recompiled for SDK 6.x to support the new V8 engine that was upgraded in that release. The version before still works the same, but is used for SDK < 6.
